# Generated by Django 4.2.1 on 2023-06-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.CharField(default='username', max_length=100),
        ),
    ]
